// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voseslzzqkqtzgtotglz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvc2VzbHp6cWtxdHpndG90Z2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDk3NjgsImV4cCI6MjA3NDI4NTc2OH0.zc3kv0Hx5mCTKj9fgLnz3PjPRJDWknF77XiNI02EkwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});